# Generated by Django 3.1.7 on 2021-03-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programming',
            old_name='names',
            new_name='name',
        ),
    ]
